name: CI

on:
  push:
    branches:
      - main   

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [Default Branch]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Setup NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm install

      - name: Run check
        run: |
          echo "Running NPM check"
          npm run check

      - name: Run build
        run: |
            npm run build

      - name: Print PWD
        run: |
          ls -la ${PWD}
          env
      
      # - name: Publish components (Github packages)
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     AFFECTED=$(npx nx print-affected --base=origin/main~1 --head=origin/main --select=projects)
      #     LIBS=($(echo $AFFECTED | tr ", " "\n"))

      #     echo $LIBS

      #     for LIB in "${LIBS[@]}"
      #     do
      #       cat ${PWD}/dist/packages/${LIB}/.npmrc
      #       echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN\n@bhenriq-souza:registry=https://npm.pkg.github.com" > ${PWD}/dist/packages/${LIB}/.npmrc

      #       ls -la ${PWD}/dist/packages/${LIB}

      #       printf "Publishing $LIB... \n"
      #       npx nx publish $LIB --args="--version=1.0.0"
      #       wait
      #     done
