name: CI

on:
  push:
    branches:
      - main   

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [Default Branch]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Setup NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm install

      - name: Run check
        run: |
          echo "Running NPM check"
          npm run check
      
      - name: Run build
        run: |
          echo "Build affected libs"
          npm run build

      - name: Print Available env
        run: env
      
      - name: Publish components (Github packages)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          AFFECTED=$(npx nx print-affected --base=origin/main~1 --head=origin/main --select=projects)
          LIBS=($(echo $AFFECTED | tr ", " "\n"))

          echo $LIBS

          for LIB in "${LIBS[@]}"
          do
            printf "Getting NPM Package version to publish $LIB... \n"
            PKG_VERSION=$(npx nx get-version $LIB)

            echo $PKG_VERSION\n

            # printf "Preparing NPM to publish $LIB... \n"
            # npx nx pre-publish $LIB --args="--token=$NPM_TOKEN" --verbose

            # printf "Publishing $LIB... \n"
            # npx nx publish $LIB --args="--version=$PKG_VERSION"  --verbose
            wait
          done
