name: CI

on:
  push:
    branches:
      - main   

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [Default Branch]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Setup NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm install

      - name: Run check
        run: |
          echo "Running NPM check"
          npm run check

      - name: Run build
        run: |
            npm run build
            
      - name: Publish components (Github packages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: chmod +x ${PWD}/.devops/publish.sh && ${PWD}/.devops/publish.sh
