name: CI

on:
  push:
    branches:
      - main   

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [Default Branch]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Setup NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          npm install

      - name: Run check
        run: |
          echo "Running NPM check"
          npm run check

      - name: Run build
        run: |
            npm run build
      
      - name: Log into NPM
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          export NPM_USERNAME=bhenriq-souza
          export NPM_PASSWORD=$NPM_TOKEN
          export NPM_EMAIL=bhenriq.souza@gmail.com

          npm adduser <<!
          $NPM_USERNAME
          $NPM_PASSWORD
          $NPM_EMAIL
          !
          

      - name: Publish components (Github packages)
        run: |
          chmod +x ${PWD}/.devops/publish.sh && ${PWD}/.devops/publish.sh
